### ISSUE TITLE
Bot doesn't respond to all messages

### ISSUE THREAD

**Issue by maaduukaar** [Endogen/idena-node-watcher#2]
Thanks for the hint, now I run it :)

But the bot doesn't respond to all messages I sent through Telegram and this warning shows in logs:

> WARNING conversationhandler.py:178 __init__()] If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.

How can I fix this?

**Comment by Endogen** [comment]
That's just a warning and not an issue. It's not related to the issue that you don't get any reply.

I would try to debug it and see if the code of the command you try to trigger is actually being access and executed. I guess not. If so, try removing all other plugins except the one you want to access and see if it works then. If yes then some other plugin is "catching" your request.

Does any command work or no command whatsoever? You can remove plugins by deleting the folder of that plugin in the "plugins" folder

**Comment by maaduukaar** [comment]
Thanks, the bot has now stabilized by itself. This error was only at the beginning, right after launch. As well as these errors:

> Idena Watcher, [06.11.20 14:26]
> 🚨 Admin Notification:
> UNIQUE constraint failed: users.user_id
> 
> Idena Watcher, [06.11.20 14:26]
> ‼️ Not possible to add user: UNIQUE constraint failed: users.user_id
> 
> Idena Watcher, [06.11.20 14:26]
> 🚨 Admin Notification:
> ‼️ Not possible to add user: UNIQUE constraint failed: users.user_id

The bot is working fine now, thanks for this project.
